[package]
name = "py-rust-hello-world"
version = "0.2.0"
authors = ["Justin Lewis <justin.lewis@gmail.com>"]

[lib]
name = "hello_world"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.2"
features = ["python-3-6"]
